name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate && npx prisma db push --accept-data-loss"
dev = "npm exec react-router dev"